meta:
  url: https://quramy.github.io/build-battle-saga-gulp/
  name: Introduction to Gulp
  author: quramy
  thumbnail: https://raw.githubusercontent.com/Quramy/build-battle-saga-gulp/master/ogp.jpg
  description: Let's enjoy writing gulpfile.js
  sns:
    - twitter
slide:
  loop: false
  sidebar: true
  targetBlank: true
  showIndex: false
  isVertical: false
  code:
    languages:
      - javascript
      - markup
      - typescript
    plugins: []
    theme: okaidia
extends:
  js:
  css: styles.css
